// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/liufu/publicWorkspace/ant-design-charts/node_modules/.pnpm/dumi@2.0.3_rv6jk35udyttn3rkr7xhh2swc4/node_modules/dumi/theme-default/slots/SearchBar/index.js';
